### ISSUE TITLE
index.js: Couldn't find preset "flow" relative to directory

### ISSUE THREAD

**Issue by smart-mickey** [react-native-community/react-native-side-menu#298]

**Comment by mounibec** [comment]
Same issue using RN 0.42.0

**Comment by CharlieOrlando** [comment]
Same, but with RN 0.44.0

**Comment by Kureev** [comment]
Hi @smart-mickey, @mounibec, @CharlieOrlando!

How can I repro this?

**Comment by Kureev** [comment]
Not sure, but it may be related to the react-native version. In the project, there is an example folder with Basic example which uses `0.46.3`. Tried to remove node_modules and install them again - can't reproduce 😞

**Comment by eduardomontalvo** [comment]
Same, but with RN 0.46.3.. and I downloaded the Basic example and got the same error :(

**Comment by Kureev** [comment]
Ok, I believe it's because of the `babel-preset-flow`. This is completely my bad and there are two ways to workaround this till I come up with a proper fix:
- To use 0.20.3 version for now
- Create a `.babelrc` with
  ```json
  {
    "presets": ["flow"]
  }
  ```
  (and therefore install `babel-preset-flow`)

In the meantime I'll create a deployment pipeline so you get only transpiled code.

P.S. Strange that `flow` preset is not added to the initial setup 🤔

**Comment by Kureev** [comment]
Ok, I've pushed `v1.0.1`. Please, give it a try and tell me if it worked. 🤞

**Comment by CharlieOrlando** [comment]
No dice. Still getting the error. Appreciate the quick responses, though

**Comment by Kureev** [comment]
Ok, so the core issue is correct: by default, React Native doesn't process `node_modules` (for some reason).

@eduardomontalvo Right, this is something I forgot to add. Will release a 1.0.2 with the fix. Although, everything should run w/o additional `.babelrc` file.

**Comment by Kureev** [comment]
`1.0.2` is out. Can you give it a try, please?

**Comment by eduardomontalvo** [comment]
Works fine!

**Comment by CharlieOrlando** [comment]
Yep. Working great. Thanks!

**Comment by Kureev** [comment]
Thank you for your feedback, guys! It won't be possible w/o you! ❤️
